### ISSUE TITLE
Scroll jumping, hover and press position issues

### ISSUE THREAD

**Issue by linasmnew** [fivecar/react-native-draglist#55] opened 2024-11-30 21:36 UTC
Hey, my first time using the package and first off thanks for maintaining it, then wanted to bring up a couple issues i've noticed running this on expo ios with a simple image uploader (using Expo 52.0.0 and this library 3.6.3):
- When scrolling to the bottom of a page, hovering over the last few items makes the scroll jump (note just a hover not a long press)
- When long pressing items for dragging the item starts dragging from the top of the image rather than the center
Making the below change here https://github.com/fivecar/react-native-draglist/blob/main/src/index.tsx#L213 seems to make it correctly point to the center though not sure if it's the right fix

from:
```
clientPos - (layouts[activeKey.current].pos + dragItemExtent / 2)
```

to:
```
clientPos - (layouts[activeKey.current].pos + dragItemExtent)
```

Example component used for testing:

```
import { useState } from 'react'
import { TouchableOpacity, Image, Button } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import DragList from 'react-native-draglist';

export default function DraggableLyrics() {
  const [images, setImages] = useState([]);

  const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ['images', 'videos'],
      aspect: [4, 3],
      quality: 1,
      allowsMultipleSelection: true
    });

    if (!result.canceled) {
      setImages(result.assets.map(asset => ({
        id: asset.fileSize,
        component: <Image style={{ width: 150, height: 150, margin: 30 }} source={{ uri: asset.uri }}/>
      })))
    }
  };

  const keyExtractor = (str, _index) => {
    return str.id;
  }

  const renderItem = info => {
    const {item, onDragStart, onDragEnd, isActive} = info;

    return (
      <TouchableOpacity
        key={item.id}
        onLongPress={onDragStart}
        onPressOut={onDragEnd}
        style={
          isActive ? { backgroundColor: 'red'} : { backgroundColor: 'blue'}
        }
      >
        { item.component }
      </TouchableOpacity>
    );
  }

  const onReordered = (fromIndex, toIndex) => {
    const copy = [...images];
    const removed = copy.splice(fromIndex, 1);
    copy.splice(toIndex, 0, removed[0]);
    setImages(copy);
  }

  return <DragList
    ListHeaderComponent={ <Button title="Pick an image from camera roll" onPress={pickImage} /> }
    data={images}
    keyExtractor={keyExtractor}
    onReordered={onReordered}
    renderItem={renderItem}
  />
}
```

**Comment by fivecar** [comment] 2024-12-01 06:26
@linasmnew : thanks for taking the time to suggest an improvement! What you recommended is a good start, though the full fix is a bit more subtle: https://github.com/fivecar/react-native-draglist/pull/57/files

We've now also fixed the first bullet point you bring up (sudden jumping), which was due to a calculation bug as well: https://github.com/fivecar/react-native-draglist/pull/58

Thanks for your great suggestions! Fixes released as [3.7.0](https://github.com/fivecar/react-native-draglist/releases/tag/3.7.0).

**Closed by fivecar** 2024-12-01 06:26 UTC

**Comment by linasmnew** [comment] 2024-12-01 08:17
Thanks @fivecar, can confirm the drag is now in fact relative to the touch position but seems like it's only behaving that way for items above the bottom of the screen, bottom items are still behaving a bit weird with the jumping scroll effect - both when hovering bottom items and when scrolling to the bottom 🤔

**Comment by linasmnew** [comment] 2024-12-01 12:27
@fivecar see https://github.com/user-attachments/assets/63d38714-9ea4-4898-9658-594a32cb3d46

I've tested the example app by adding images to it instead of text and i'm getting the same behaviour as that vid ☝️ so i believe the example app needs to be more varied it would probably help having all 3 examples on their own pages taking up full height of the screen to capture more scenarios, i'd be happy to add more examples if you are open it

**Comment by fivecar** [comment] 2024-12-02 20:48
@linasmnew : can you describe in words what's wrong with the two videos you linked above? In the first video, I'm not positive what's happening, but it seems like you dragged one item in order to scroll the list -- is that right? And if so, is the problem that the item flashes?

In the second video's case, I'm also not quite sure I can tell from the video what's wrong. Could you try describing the unexpected behavior a bit more? (BTW, wrapping a FlatList inside a ScrollView generates a lot of issues which RN was warned about for many years...)
